webapp/mycars/mycars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from catalogo.views import ricerca_auto

urlpatterns = [
    path('', ricerca_auto),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/mycars/catalogo/models.py
from django.db import models

# Create your models here.
class Costruttore(models.Model):
    class Meta:
        verbose_name_plural = "Costruttori"

    nome = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.nome

TIPI_ALIMENTAZIONE = (
    ('b', "Benzina"),
    ('d', "Diesel"),
    ('g', "GPL"),
    ('m', "Metano"),
    ('e', "Elettrica"),
    ('i', "Ibrida"),
)

class Auto(models.Model):
    
    class Meta:
        verbose_name_plural = "Auto"

    costruttore = models.ForeignKey(Costruttore, on_delete=models.PROTECT)
    modello = models.CharField(max_length=50)
    anno = models.IntegerField()
    
    alimentazione = models.CharField(max_length=3, choices=TIPI_ALIMENTAZIONE)
    km = models.IntegerField(blank=True, default=0)

    fotografia = models.ImageField(blank=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return "{} {} anno {}".format(self.costruttore, self.modello, self.anno)
     

webapp/mycars/catalogo/views.py
import django_filters
from django.shortcuts import render

from catalogo.models import Auto


class AutoFilter(django_filters.FilterSet):
    class Meta:
        model = Auto
        fields = ['costruttore', 'modello', 'anno']


def ricerca_auto(request):
    filtro = AutoFilter(request.GET, queryset=Auto.objects.all())
    return render(request, 'ricerca_auto.html', {'filter': filtro})

webapp/mycars/catalogo/templates/ricerca_auto.html
{% load bootstrap4 static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}

    <title>Cerca Auto</title>
  </head>
  <body>
    <h1>Cerca un'auto:</h1>
    <div class="container">
        <div class="row">
            <div class="col-3">
                <form action="" method="get" class="form">
                    {% bootstrap_form filter.form %}
                    {% buttons %}
                      <button type="submit" class="btn btn-primary">
                        Cerca
                      </button>
                    {% endbuttons %}
                  </form>   
            </div>
            <div class="col-9">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Costruttore</th>
                    <th scope="col">Modello</th>
                    <th scope="col">Anno</th>
                    <th scope="col">Alimentazione</th>
                    <th scope="col">Km</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Note</th>
                  </tr>
                </thead>
                <tbody>
                {% for auto in filter.qs %}
                  <tr>
                    <th scope="row">{{ auto.id }}</th>
                    <td>{{ auto.costruttore }}</td>
                    <td>{{ auto.modello }}</td>
                    <td>{{ auto.anno }}</td>
                    <td>{{ auto.get_alimentazione_display }}</td>
                    <td>{{ auto.km }}</td>
                    <td><img src="{{ auto.fotografia.url }}" width=200></td>
                    <td>{{ auto.note }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
    </div>
</body>
</html>